name: black

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Run black
        run: black $(git ls-files '*.py')
      - name: Commit formatted code
        run: |
          git config --local user.name 'github-actions'
          git config --local user.email 'github-actions@github.com'
          git add .
          git commit -m "Format code with black" || echo "No changes to commit"
          git push