name: 'Quality Gates'

on:
  push:
    branches: ['main']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: '--diff --check --verbose'

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reposityory
        uses: actions/checkout@v4
      - name: Setup docker
        uses: docker/setup-buildx-action@v3
      - name: Build docker image
        run: docker build -t tests_image:latest .
      - name: Run tests
        run: docker run tests_image
