name: 'Quality Gates'

on:
  push:
    branches: ['main']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: '--diff --check --verbose'
